version: "3"
services:

  account-db:
    container_name: account-db
    image: postgres:12
    environment:
      TZ: Europe/Tallinn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-setup-account.sql:/docker-entrypoint-initdb.d/db-setup.sql
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=115 -c max_prepared_transactions=100
    ports:
      - 5491:5432

  order-db:
    container_name: order-db
    image: postgres:12
    environment:
      TZ: Europe/Tallinn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-setup-order.sql:/docker-entrypoint-initdb.d/db-setup.sql
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=115 -c max_prepared_transactions=100
    ports:
      - 5492:5432

  product-db:
    container_name: product-db
    image: postgres:12
    environment:
      TZ: Europe/Tallinn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-setup-product.sql:/docker-entrypoint-initdb.d/db-setup.sql
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=115 -c max_prepared_transactions=100
    ports:
      - 5493:5432